version: '3'
services:
  crawler:
    image: crawler
    build: ./api
    ports:
      - 8080:8080

  elasticsearch:
    image: elasticsearch:7.0.0
    environment:
      - node.name=es01
      - cluster.initial_master_nodes=es01
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200


  kibana:
    image: kibana:7.0.0
    ports:
      - 5601:5601
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
